version: "3.9"
services:
  website:
    build: .
    env_file:
      - db.env
    ports:
      - "43000:8080"
    environment:
      profile: "prod"
    networks:
      - db-net
    depends_on:
      - "db"
  db:
    image: "postgres:9.6-alpine"
    env_file:
      - db.env
    ports:
      - "5432:5432"
    networks:
      - db-net
networks:
  db-net:
    driver: bridge