name: Sonar and build checks

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag tests:$(date +%s)

  sonar-checks-back:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Check Sonar report for backend
        run: cd moneyetdystopie-back && mvn clean install spotbugs:check sonar:sonar -Dspring.profiles.active=dev -Dsonar.projectBaseDir=moneyetdystopie-back -Dsonar.projectKey=${{secrets.SONAR_PROJECT_BACK}} -Dsonar.host.url=${{secrets.SONAR_URL_BACK}} -Dsonar.login=${{secrets.SONAR_LOGIN_BACK}} -Dsonar.qualitygate.wait=true

  sonar-checks-front:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Install modules
        run: cd moneyetdystopie-front && npm install
      - name: Generate ESLint report
        run: cd moneyetdystopie-front && npm run eslint
      - name: Correct paths referenced in report
        run: cd moneyetdystopie-front && sed -i 's+/home/runner/work/ivvq-projet-2021-money-et-dystopie/ivvq-projet-2021-money-et-dystopie+/github/workspace+g' target/report.json
      - name: Build front
        run: cd moneyetdystopie-front && npm run build
      - name: Launch Cypress tests
        run: cd moneyetdystopie-front && npm run serve-and-test
      - name: Check Sonar report for frontend
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{secrets.SONAR_LOGIN_FRONT}}
        with:
          projectBaseDir: moneyetdystopie-front
          args: >
            -Dsonar.projectKey=${{secrets.SONAR_PROJECT_FRONT}}
            -Dsonar.host.url=${{secrets.SONAR_URL_FRONT}}
            -Dsonar.login=${{secrets.SONAR_LOGIN_FRONT}}
            -Dsonar.qualitygate.wait=true
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info